<?php
/**
 * Title: Homepage hero
 * Slug: longevity-starter/homepage-hero
 * Categories: featured, banner
 * Inserter: true
 */
?>
<!-- wp:group {"align":"full","className":"longevity-hero","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull longevity-hero"><!-- wp:group {"align":"wide","layout":{"type":"constrained","contentSize":"880px","justifyContent":"left"}} --><div class="wp-block-group alignwide"><!-- wp:paragraph {"className":"longevity-eyebrow"} --><p class="longevity-eyebrow">Independent health evidence and consumer testing</p><!-- /wp:paragraph --><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Understand what works, what is uncertain, and what is worth considering.</h1><!-- /wp:heading --><!-- wp:paragraph {"className":"longevity-hero-copy"} --><p class="longevity-hero-copy">We examine health claims and consumer products with documented evidence, visible limitations, and transparent methods. Our editorial independence and corrections policy keep the information you see accountable.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( \Longevity\Core\Routes::public_page_url( 'start_here' ) ); ?>">Start Here</a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="/category/evidence-literacy/">Browse Evidence Guides</a></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:group {"className":"longevity-trust-signals","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"left"}} --><div class="wp-block-group longevity-trust-signals"><!-- wp:paragraph {"className":"longevity-trust-signal"} --><p class="longevity-trust-signal">Evidence graded</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"longevity-trust-signal"} --><p class="longevity-trust-signal">Testing documented</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"longevity-trust-signal"} --><p class="longevity-trust-signal">Conflicts disclosed</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group -->
