#!/bin/sh
# Single-quoted php/awk/jq snippets below are intentional (no shell expansion).
# shellcheck disable=SC2016
set -eu

required="WP_SITE_URL WP_SITE_TITLE WP_ADMIN_USER WP_ADMIN_PASSWORD WP_ADMIN_EMAIL WP_ENVIRONMENT_TYPE WP_TIMEZONE WP_LOCALE"
for key in $required; do
  eval "value=\${$key-}"
  [ -n "$value" ] || { echo "ERROR: $key is required." >&2; exit 1; }
done

case "$(printf '%s' "$WP_ADMIN_USER" | tr '[:upper:]' '[:lower:]')" in
  admin|administrator|root|wordpress|wpadmin|site_admin)
    echo "ERROR: Refusing a commonly targeted administrator username." >&2
    exit 1
    ;;
esac

[ "${#WP_ADMIN_PASSWORD}" -ge 16 ] || { echo "ERROR: WP_ADMIN_PASSWORD must be at least 16 characters." >&2; exit 1; }
printf '%s' "$WP_ADMIN_PASSWORD" | grep -Eiq '(change-me|replace|password|placeholder)' && { echo "ERROR: WP_ADMIN_PASSWORD is a placeholder." >&2; exit 1; }
printf '%s' "$WP_ADMIN_EMAIL" | grep -Eq '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' || { echo "ERROR: WP_ADMIN_EMAIL is invalid." >&2; exit 1; }

# Use PHP's database driver for readiness. The MariaDB client bundled with the
# WP-CLI image can reject MySQL 8.4's self-signed development certificate even
# though WordPress can connect successfully.
attempt=0
max_attempts=${DB_READINESS_ATTEMPTS:-40}
while :; do
  if php -r '
mysqli_report(MYSQLI_REPORT_OFF);
$connection = @mysqli_connect(
    getenv("WORDPRESS_DB_HOST"),
    getenv("WORDPRESS_DB_USER"),
    getenv("WORDPRESS_DB_PASSWORD"),
    getenv("WORDPRESS_DB_NAME")
);
exit($connection ? 0 : 1);
  '; then
    break
  fi
  attempt=$((attempt + 1))
  if [ "$attempt" -ge "$max_attempts" ]; then
    echo "ERROR: Database was not ready after $max_attempts attempts. Check the isolated environment credentials and database volume." >&2
    exit 1
  fi
  echo "Waiting for the database..."
  sleep 3
done

if ! wp core is-installed --allow-root; then
  wp core install \
    --url="$WP_SITE_URL" \
    --title="$WP_SITE_TITLE" \
    --admin_user="$WP_ADMIN_USER" \
    --admin_password="$WP_ADMIN_PASSWORD" \
    --admin_email="$WP_ADMIN_EMAIL" \
    --locale="$WP_LOCALE" \
    --skip-email \
    --allow-root
fi

wp theme activate longevity-starter --allow-root
wp rewrite structure '/%postname%/' --hard --allow-root
wp option update blogdescription 'Transparent evidence reviews and reproducible consumer testing with clearly stated uncertainty.' --allow-root
wp option update timezone_string "$WP_TIMEZONE" --allow-root
wp option update default_comment_status closed --allow-root
wp option update default_ping_status closed --allow-root
wp option update users_can_register 0 --allow-root
wp option update blog_public 0 --allow-root

# Remove WordPress default plugins and themes that pollute the bind-mounted
# wp-content directory. These are generated by WordPress core at runtime and
# must not appear in the source checkout or trigger allowlist validation.
wp plugin delete akismet hello --allow-root 2>/dev/null || true
wp theme delete twentytwentyfive twentytwentyfour twentytwentythree --allow-root 2>/dev/null || true

# Schema migrations must precede content bootstrap: they create the audit
# tables and register role capabilities. On a fresh database the trust-page
# guard (approve_publication) and mandatory audit writes fail without them.
wp longevity migrate --user="$WP_ADMIN_USER" --allow-root

# The canonical application bootstrap. Pages, categories, and draft launch
# records are defined once in longevity-core (Bootstrap_Command) and mirrored
# by the route-state contract in config/routes.json. The command is
# idempotent: a second run creates nothing and changes no approval data.
wp longevity bootstrap all --allow-root

# Seed draft trust pages with content from the Git templates. Templates are
# one-time seeds; the script refuses to overwrite a published or approved
# page, and publication still requires a named human trust-page approval.
wp eval-file /scripts/populate-trust-pages.php --user="$WP_ADMIN_USER" --allow-root

if [ "${INSTALL_OPTIONAL_PLUGINS:-0}" = "1" ]; then
  wp plugin install wordpress-seo --activate --allow-root || true
  wp plugin install google-site-kit --activate --allow-root || true
fi

wp cache flush --allow-root
printf '\nBootstrap complete: %s\n' "$WP_SITE_URL"
printf 'Policy and legal pages remain drafts until accountable human approval.\n'
printf 'Search-engine visibility remains disabled; enable it only at production launch.\n'
